# -*- coding: utf-8 -*-
"""Re-extract RAW image blobs from the full DB backup (web_app/data_full.db)
into public/img/{yaotu,renji,tianji}/ and (re)generate web_app/img_index.py.

IMPORTANT: The image blobs in the SQLite DB are stored RAW (already decrypted).
An earlier version wrongly applied XOR-0x0F and corrupted every file. This
version writes the bytes as-is. JPEGs (yaotu/renji) are re-encoded at
JPEG_QUALITY to shrink the Vercel Hobby upload below the 100 MB source limit;
PNGs (tianji diagrams) are kept raw since they are already well-compressed.

The source is the full backup data_full.db (data.db already had its image
tables dropped). Nothing is dropped here; data_full.db stays intact as the
local-only backup (excluded by .vercelignore, never uploaded).
"""
import os
import sqlite3
from io import BytesIO

try:
    from PIL import Image
    HAVE_PIL = True
except Exception:
    HAVE_PIL = False

HERE = os.path.dirname(os.path.abspath(__file__))              # tools/
WEB = os.path.abspath(os.path.join(HERE, "..", "web_app"))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
FULL = os.path.join(WEB, "data_full.db")   # source: full backup w/ image tables
DB = os.path.join(WEB, "data.db")          # shrunk text-only DB (no image tables)

IMG = [("yaotu_img", "yaotu"), ("renji_img", "renji"), ("tianji_img", "tianji")]
JPEG_QUALITY = 80

EXT_MAP = {"image/png": "png", "image/gif": "gif", "image/jpeg": "jpg",
           "image/jpg": "jpg"}


def ext_of(ct):
    ct = (ct or "").lower()
    if ct in EXT_MAP:
        return EXT_MAP[ct]
    if "png" in ct:
        return "png"
    if "gif" in ct:
        return "gif"
    return "jpg"


def sane(n):
    for ch in '/\\:*?"<>|\r\n\t':
        n = n.replace(ch, "_")
    return (n.strip() or "img")


def main():
    src = FULL if os.path.exists(FULL) else DB
    if not os.path.exists(src):
        print("source DB not found:", src)
        return
    index = {"yaotu": {}, "renji": {}, "tianji": {}}
    con = sqlite3.connect(src)
    cur = con.cursor()
    total = 0
    for tbl, sub in IMG:
        try:
            cur.execute("SELECT name, data, ctype FROM %s" % tbl)
        except sqlite3.OperationalError:
            print("  %s: no such table (skipped)" % tbl)
            continue
        d = os.path.join(ROOT, "public", "img", sub)
        os.makedirs(d, exist_ok=True)
        used = set()
        n = 0
        for name, blob, ct in cur.fetchall():
            if not blob:
                continue
            ext = ext_of(ct)
            base = sane(name)
            fn = base + "." + ext
            k = 2
            while fn in used:
                fn = "%s_%d.%s" % (base, k, ext)
                k += 1
            used.add(fn)
            out = os.path.join(d, fn)
            if HAVE_PIL and ext == "jpg":
                try:
                    im = Image.open(BytesIO(blob))
                    im = im.convert("RGB")
                    im.save(out, "JPEG", quality=JPEG_QUALITY, optimize=True,
                            progressive=True)
                except Exception as e:
                    print("  reencode fail %s: %s -> write raw" % (fn, e))
                    with open(out, "wb") as f:
                        f.write(blob)
            else:
                with open(out, "wb") as f:
                    f.write(blob)
            index[sub][name] = fn
            n += 1
        total += n
        print("  %s -> public/img/%s : %d files" % (tbl, sub, n))
    con.close()
    print("extracted", total, "images total")

    # write img_index.py (kept in web_app/ so it ships inside the function bundle)
    idx_path = os.path.join(WEB, "img_index.py")
    with open(idx_path, "w", encoding="utf-8") as f:
        f.write("# -*- coding: utf-8 -*-\n")
        f.write("# AUTO-GENERATED by tools/extract_images.py -- do not edit.\n")
        f.write("# Maps original image name -> filename under public/img/{sub}/.\n")
        f.write("IMG_INDEX = {\n")
        for sub in ("yaotu", "renji", "tianji"):
            f.write("  %r: {\n" % sub)
            for name, fn in index[sub].items():
                f.write("    %r: %r,\n" % (name, fn))
            f.write("  },\n")
        f.write("}\n")
    print("wrote", idx_path, "(%d entries)" % sum(len(v) for v in index.values()))


if __name__ == "__main__":
    main()
